name: Compare Test Coverage

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare against'
        required: true
        default: 'main'
      compare_branch:
        description: 'Branch to compare'
        required: true
        default: '**'

jobs:
  compare-coverage:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: 
          - codemod
          - react
          - react-base
          - react-docs
          - react-hooks
          - styled-system
          - theme
          - utils

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # - name: Install Yarn globally
      #   run: npm install -g yarn
      - name: restore dependencies
        id: restore-dependencies
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.WORKING_DIRECTORY }}/node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Install yarn dependencies for main branch
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: Install dependencies
        run: yarn build

      - name: Run tests on main branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from main branch
        run: |
          mkdir -p coverage-main/${{ matrix.package }}
          cp packages/${{ matrix.package }}/coverage/coverage-summary.json coverage-main/${{ matrix.package }}/
        
      - name: Checkout compare branch
        uses: actions/checkout@v2
        with:
          clean: false
          ref: ${{ github.event.inputs.compare_branch }}

      - name: Install yarn dependencies for input branch
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: Install dependencies
        run: yarn build

      - name: cache dependencies
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        id: cache-dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            .venv
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Run tests on input branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from input branch
        run: |
          mkdir -p coverage-input/${{ matrix.package }}
          cp packages/${{ matrix.package }}/coverage/coverage-summary.json coverage-input/${{ matrix.package }}/

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Compare coverage and set output
        id: compare
        run: |
          base_coverage=$(jq '.total | {functions: .functions.pct}' coverage-base/${{ matrix.package }}/coverage-summary.json)
          compare_coverage=$(jq '.total | {functions: .functions.pct}' coverage-compare/${{ matrix.package }}/coverage-summary.json)

          base_functions=$(echo $base_coverage | jq -r '.functions')
          compare_functions=$(echo $compare_coverage | jq -r '.functions')

          echo "Package: ${{ matrix.package }}"
          echo "Base branch function coverage: $base_functions"
          echo "Compare branch function coverage: $compare_functions"

          if (( $(echo "$compare_functions > $base_functions" | bc -l) )); then
            echo "::set-output name=coverage_increase::true"
            echo "Function coverage in ${{ github.event.inputs.compare_branch }} is greater than ${{ github.event.inputs.base_branch }} for package ${{ matrix.package }}."
          else
            echo "Function coverage in ${{ github.event.inputs.compare_branch }} is not greater than ${{ github.event.inputs.base_branch }} for package ${{ matrix.package }}."
          fi
  create-pr:
    needs: compare-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create PR
        if: steps.compare.outputs.coverage_increase == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create --title "Increase function coverage" --body "One or more packages have increased function coverage." --base ${{ github.event.inputs.base_branch }} --head ${{ github.event.inputs.compare_branch }}
