name: Compare Test Coverage

on:
  push:
    branches:
      - main
      - feature/lillian

jobs:
  compare-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # - name: Install Yarn globally
      #   run: npm install -g yarn

      - name: Install yarn dependencies for main branch
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn install

      - name: Install dependencies
        run: yarn build

      - name: Run tests on main branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from main branch
        run: |
          mkdir -p coverage-main
          cp -r packages/react/coverage/lcov-report coverage-main/
        
      - name: Checkout input branch
        uses: actions/checkout@v2
        with:
          clean: false
          ref: ${{ github.event.inputs.branch }}

      - name: Install yarn dependencies for input branch
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn install

      - name: Install dependencies
        run: yarn build

      - name: Run tests on input branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from input branch
        run: |
          mkdir -p coverage-input
          cp -r packages/react/coverage/lcov-report coverage-input/

      - name: Compare coverage
        run: |
          # Extract and compare coverage rates
          main_statements=$(grep -Po 'Statements\s+<span class="strong">\K[^%]+' coverage-main/lcov-report/index.html)
          main_branches=$(grep -Po 'Branches\s+<span class="strong">\K[^%]+' coverage-main/lcov-report/index.html)
          main_functions=$(grep -Po 'Functions\s+<span class="strong">\K[^%]+' coverage-main/lcov-report/index.html)
          main_lines=$(grep -Po 'Lines\s+<span class="strong">\K[^%]+' coverage-main/lcov-report/index.html)

          input_statements=$(grep -Po 'Statements\s+<span class="strong">\K[^%]+' coverage-input/lcov-report/index.html)
          input_branches=$(grep -Po 'Branches\s+<span class="strong">\K[^%]+' coverage-input/lcov-report/index.html)
          input_functions=$(grep -Po 'Functions\s+<span class="strong">\K[^%]+' coverage-input/lcov-report/index.html)
          input_lines=$(grep -Po 'Lines\s+<span class="strong">\K[^%]+' coverage-input/lcov-report/index.html)

          echo "Main branch coverage:"
          echo "Statements: $main_statements%"
          echo "Branches: $main_branches%"
          echo "Functions: $main_functions%"
          echo "Lines: $main_lines%"

          echo "Input branch coverage:"
          echo "Statements: $input_statements%"
          echo "Branches: $input_branches%"
          echo "Functions: $input_functions%"
          echo "Lines: $input_lines%"

          if (( $(echo "$input_statements < $main_statements" | bc -l) )); then
            echo "Input branch statements coverage is lower than main branch"
            exit 1
          fi
          if (( $(echo "$input_branches < $main_branches" | bc -l) )); then
            echo "Input branch branches coverage is lower than main branch"
            exit 1
          fi
          if (( $(echo "$input_functions < $main_functions" | bc -l) )); then
            echo "Input branch functions coverage is lower than main branch"
            exit 1
          fi
          if (( $(echo "$input_lines < $main_lines" | bc -l) )); then
            echo "Input branch lines coverage is lower than main branch"
            exit 1
          fi

          echo "Input branch coverage is equal or better than main branch"
      # - name: Compare coverage
      #   run: |
      #     main_coverage=$(grep -Po 'All files.*?\K(\d+\.\d+%)' coverage-main/lcov-report/index.html)
      #     input_coverage=$(grep -Po 'All files.*?\K(\d+\.\d+%)' coverage-input/lcov-report/index.html)
      #     echo "Main branch coverage: $main_coverage"
      #     echo "Input branch coverage: $input_coverage"
      #     if (( $(echo "$input_coverage < $main_coverage" | bc -l) )); then
      #       echo "Input branch coverage is lower than main branch"
      #       exit 1
      #     fi