name: Compare Test Coverage

on:
  push:
    branches:
      - main
      - feature/lillian

jobs:
  compare-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install node modules
        run: yarn run ci
      - name: Install dependencies
        run: yarn build

      - name: Run tests on main branch
        run: yarn test

      - name: Checkout input branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies
        run: yarn build

      - name: Run tests on main branch
        run: yarn test