name: Compare Test Coverage

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare against'
        required: true
        default: 'v2'
      compare_branch:
        description: 'Branch to compare'
        required: true
        default: '**'

jobs:
  get-base-branch-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: restore dependencies
        id: restore-dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Install yarn dependencies for main branch
        shell: bash
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Run tests on main branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from main branch
        run: |
          mkdir -p coverage-main
          for dir in packages/*/coverage; do
            if [ -d "$dir" ]; then
              package=$(basename $(dirname $dir))
              mkdir -p coverage-main/$package
              cp $dir/coverage-summary.json coverage-main/$package/
            fi
          done

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-main
          path: coverage-main

      - name: cache dependencies
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        id: cache-dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            cache-dependencies-

  get-compared-branch-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compare branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.compare_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: restore dependencies
        id: restore-dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Install yarn dependencies for compared branch
        shell: bash
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Run tests on compared branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from compared branch
        run: |
          mkdir -p coverage-compared
          for dir in packages/*/coverage; do
            if [ -d "$dir" ]; then
              package=$(basename $(dirname $dir))
              mkdir -p coverage-compared/$package
              cp $dir/coverage-summary.json coverage-compared/$package/
            fi
          done

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-compared
          path: coverage-compared

      - name: cache dependencies
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        id: cache-dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            cache-dependencies-

  compare-coverage:
    needs:
      - get-base-branch-coverage
      - get-compared-branch-coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - codemod
          - react
          - react-base
          - react-hooks
          - styled-system
          - theme
          - utils
    outputs:
      coverage-increased: ${{ steps.compare.outputs.COVERAGE_INCREASE }}
      codemod-main-branch-coverage: ${{ steps.compare.outputs.CODEMODE_MAIN_BRANCH_COVERAGE }}
      codemod-compared-branch-coverage: ${{ steps.compare.outputs.CODEMODE_COMPARED_BRANCH_COVERAGE }}
      react-branch-coverage: ${{ steps.compare.outputs.REACT_MAIN_BRANCH_COVERAGE }}
      react-compared-branch-coverage: ${{ steps.compare.outputs.REACT_COMPARED_BRANCH_COVERAGE }}
      react-base-main-branch-coverage: ${{ steps.compare.outputs.REACT_BASE_MAIN_BRANCH_COVERAGE }}
      react-base-compared-branch-coverage: ${{ steps.compare.outputs.REACT_BASE_COMPARED_BRANCH_COVERAGE }}
      react-hooks-main-branch-coverage: ${{ steps.compare.outputs.REACT_HOOKS_MAIN_BRANCH_COVERAGE }}
      react-hooks-compared-branch-coverage: ${{ steps.compare.outputs.REACT_HOOKS_COMPARED_BRANCH_COVERAGE }}
      styled-system-main-branch-coverage: ${{ steps.compare.outputs.STYLED_SYSTEM_MAIN_BRANCH_COVERAGE }}
      styled-system-compared-branch-coverage: ${{ steps.compare.outputs.STYLED_SYSTEM_COMPARED_BRANCH_COVERAGE }}
      theme-main-branch-coverage: ${{ steps.compare.outputs.THEME_MAIN_BRANCH_COVERAGE }}
      theme-compared-branch-coverage: ${{ steps.compare.outputs.THEME_COMPARED_BRANCH_COVERAGE }}
      utils-main-branch-coverage: ${{ steps.compare.outputs.UTILS_MAIN_BRANCH_COVERAGE }}
      utils-compared-branch-coverage: ${{ steps.compare.outputs.UTILS_COMPARED_BRANCH_COVERAGE }}
      
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-main
          path: coverage-main

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-compared
          path: coverage-compared

      - name: Compare coverage and set environment variable
        id: compare
        run: |
          main_coverage=$(jq '.total | {functions: .functions.pct}' coverage-main/${{ matrix.package }}/coverage-summary.json)
          compared_coverage=$(jq '.total | {functions: .functions.pct}' coverage-compared/${{ matrix.package }}/coverage-summary.json)

          main_functions=$(echo $main_coverage | jq -r '.functions')
          input_functions=$(echo $compared_coverage | jq -r '.functions')

          echo "Package: ${{ matrix.package }}"
          echo "Main branch function coverage: $main_functions"
          echo "Input branch function coverage: $input_functions"
          echo "$(echo ${{ matrix.package }} | tr '[:lower:]' '[:upper:]')_MAIN_BRANCH_COVERAGE=$main_functions" >> $GITHUB_ENV
          echo "$(echo ${{ matrix.package }} | tr '[:lower:]' '[:upper:]')_COMPARED_BRANCH_COVERAGE=$input_functions" >> $GITHUB_ENV

          if (( $(echo "$input_functions > $main_functions" | bc -l) )); then
            echo "Function coverage in ${{ github.ref }} is greater or equal than main for package ${{ matrix.package }}."
            echo "COVERAGE_INCREASE=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

  create-pr:
    needs: compare-coverage
    runs-on: ubuntu-latest
    if: needs.compare-coverage.outputs.coverage-increased == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create PR to merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create \ 
          --body "One or more packages have increased function coverage.\n
                  Codemod main branch coverage: ${{ needs.compare-coverage.outputs.codemod-main-branch-coverage }}\n
                  Codemod compared branch coverage: ${{ needs.compare-coverage.outputs.codemod-compared-branch-coverage }}\n
                  React main branch coverage: ${{ needs.compare-coverage.outputs.react-branch-coverage }}\n
                  React compared branch coverage: ${{ needs.compare-coverage.outputs.react-compared-branch-coverage }}\n
                  React base main branch coverage: ${{ needs.compare-coverage.outputs.react-base-main-branch-coverage }}\n
                  React base compared branch coverage: ${{ needs.compare-coverage.outputs.react-base-compared-branch-coverage }}\n
                  React hooks main branch coverage: ${{ needs.compare-coverage.outputs.react-hooks-main-branch-coverage }}\n
                  React hooks compared branch coverage: ${{ needs.compare-coverage.outputs.react-hooks-compared-branch-coverage }}\n
                  Styled system main branch coverage: ${{ needs.compare-coverage.outputs.styled-system-main-branch-coverage }}\n
                  Styled system compared branch coverage: ${{ needs.compare-coverage.outputs.styled-system-compared-branch-coverage }}\n
                  Theme main branch coverage: ${{ needs.compare-coverage.outputs.theme-main-branch-coverage }}\n
                  Theme compared branch coverage: ${{ needs.compare-coverage.outputs.theme-compared-branch-coverage }}\n
                  Utils main branch coverage: ${{ needs.compare-coverage.outputs.utils-main-branch-coverage }}\n
                  Utils compared branch coverage: ${{ needs.compare-coverage.outputs.utils-compared-branch-coverage }}"
          --base ${{ github.event.inputs.base_branch }} 
          --head ${{ github.event.inputs.compare_branch }}
