name: Compare Test Coverage

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare against'
        required: true
        default: 'v2'
      compare_branch:
        description: 'Branch to compare'
        required: true
        default: '**'

jobs:
  get-base-branch-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: restore dependencies
        id: restore-dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Install yarn dependencies for main branch
        shell: bash
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Run tests on main branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from main branch
        run: |
          mkdir -p coverage-main
          for dir in packages/*/coverage; do
            if [ -d "$dir" ]; then
              package=$(basename $(dirname $dir))
              mkdir -p coverage-main/$package
              cp $dir/coverage-summary.json coverage-main/$package/
            fi
          done

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-main
          path: coverage-main

      - name: cache dependencies
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        id: cache-dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            cache-dependencies-

  get-compared-branch-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compare branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.compare_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: restore dependencies
        id: restore-dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Install yarn dependencies for compared branch
        shell: bash
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: Run tests on compared branch
        run: yarn test --coverage
        env:
          CI: true

      - name: Save coverage report from compared branch
        run: |
          mkdir -p coverage-compared
          for dir in packages/*/coverage; do
            if [ -d "$dir" ]; then
              package=$(basename $(dirname $dir))
              mkdir -p coverage-compared/$package
              cp $dir/coverage-summary.json coverage-compared/$package/
            fi
          done

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-compared
          path: coverage-compared

      - name: cache dependencies
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        id: cache-dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: cache-dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            cache-dependencies-

  compare-coverage:
    needs:
      - get-base-branch-coverage
      - get-compared-branch-coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - codemod
          - react
          - react-base
          - react-hooks
          - styled-system
          - theme
          - utils
    outputs:
      coverage-increased: ${{ steps.compare.outputs.COVERAGE_INCREASE }}
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-main
          path: coverage-main

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-compared
          path: coverage-compared

      - name: Compare coverage and set environment variable
        id: compare
        run: |
          main_coverage=$(jq '.total | {functions: .functions.pct}' coverage-main/${{ matrix.package }}/coverage-summary.json)
          compared_coverage=$(jq '.total | {functions: .functions.pct}' coverage-compared/${{ matrix.package }}/coverage-summary.json)

          main_functions=$(echo $main_coverage | jq -r '.functions')
          input_functions=$(echo $compared_coverage | jq -r '.functions')

          echo "Package: ${{ matrix.package }}"
          echo "Main branch function coverage: $main_functions"
          echo "Input branch function coverage: $input_functions"

          if (( $(echo "$input_functions > $main_functions" | bc -l) )); then
            echo "Function coverage in ${{ github.ref }} is greater or equal than main for package ${{ matrix.package }}."
            echo "COVERAGE_INCREASE=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

  create-pr:
    needs: compare-coverage
    runs-on: ubuntu-latest
    if: needs.compare-coverage.outputs.coverage-increased == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.inputs.base_branch }}
          branch: ${{ github.event.inputs.compare_branch }}
          title: Unit test coverage increased

